const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
assert(html.includes('id="boxPlacementButton"'));assert(html.includes('Y+110 mm'));
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
// These two nodes are generated by renderCards(), not literal HTML markup.
ids.add('movelStatus-left_arm');ids.add('movelStatus-right_arm');
const map=new Map(), el=id=>{
  if(!ids.has(id))return null;
  if(!map.has(id))map.set(id,{value:'',disabled:false,hidden:false,textContent:'',dataset:{},listeners:{},addEventListener(type,fn){(this.listeners[type]??=[]).push(fn)},removeAttribute(){}});
  return map.get(id);
};
const ctx=vm.createContext({document:{getElementById:el,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},Date,Number,Boolean,Object,Array,JSON,setTimeout:()=>1,clearTimeout:()=>{}});
const code=fs.readFileSync(path.join(root,'static/app.js'),'utf8');
vm.runInContext(code.slice(0,code.lastIndexOf('\nrenderCards();')),ctx);
const run=s=>vm.runInContext(s,ctx);
run('bindEvents()');
assert.equal(el('boxPlacementButton').listeners.click?.length,1,'placement button must have exactly one click handler');
run("serverStatus={armed:true,suction:{available:true},placement:{version:'placement-v7'}};gripperState={unlocked:false};stopChassis=()=>{};updatePlacementControls()");
assert(el('boxPlacementButton').disabled);
run("renderPoseResult({usable:true,selected_target:'basket',result_id:'basket-left',localization:{valid:true,left_shoulder_frame:'left_arm_sdk_world',point_left_shoulder_mm:[500,-80,-400]},response:{}})");
assert(!el('boxPlacementButton').disabled);assert(el('placementButton').disabled);
assert(el('boxPlacementStatus').textContent.includes('Y=30'));
run("selectPoseTarget()");assert(!el('boxPlacementButton').disabled);
const requests=[];let release;
ctx.fetch=async(url,o)=>{requests.push({url,body:JSON.parse(o.body)});await new Promise(r=>release=r);return{ok:true,json:async()=>({ok:true,data:{active:true,sku_typ:'box'}})}};
(async()=>{
  const pending=el('boxPlacementButton').listeners.click[0]({type:'click',currentTarget:el('boxPlacementButton')});
  assert(el('boxPlacementButton').disabled);assert(el('placementButton').disabled);assert(el('poseEstimateButton').disabled);
  await run("executePlacement('box')");assert.equal(requests.length,1);
  assert.deepEqual(requests[0],{url:'/api/placement/start',body:{source_result_id:'basket-left',sku_typ:'box'}});
  release();await pending;assert(!el('placementStop').disabled);
  assert(!el('placementStatus').textContent.includes('夹爪'));
  run("placementExecution={active:false,phase:'idle'};serverStatus.placement.version='placement-v1';updatePlacementControls()");
  assert(el('boxPlacementButton').disabled);
  run("serverStatus.placement.version='placement-v7';renderPoseResult({usable:false,selected_target:'basket',localization:{valid:false},response:{}})");
  assert(el('boxPlacementButton').disabled);
  console.log('PASS box placement: real HTML IDs, independent left basket, locked right gripper, dynamic Y, one-shot request, mutex and stale backend/result guards');
})().catch(e=>{console.error(e);process.exitCode=1});
