const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
ids.add('movelStatus-left_arm');ids.add('movelStatus-right_arm');
const elements=new Map(),el=id=>{
  assert(ids.has(id),`unknown HTML id ${id}`);
  if(!elements.has(id))elements.set(id,{value:'',disabled:false,hidden:false,textContent:'',dataset:{},listeners:{},addEventListener(t,f){(this.listeners[t]??=[]).push(f)},removeAttribute(){}});
  return elements.get(id);
};
const ctx=vm.createContext({document:{getElementById:el,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},Date,Number,Boolean,Object,Array,JSON,setTimeout:()=>1,clearTimeout:()=>{}});
const code=fs.readFileSync(path.join(root,'static/app.js'),'utf8');
vm.runInContext(code.slice(0,code.lastIndexOf('\nrenderCards();')),ctx);
const run=s=>vm.runInContext(s,ctx);
run('bindEvents();stopChassis=()=>{}');
assert.equal(el('tubePlacementButton').listeners.click.length,1);
run("serverStatus={armed:true,placement:{version:'placement-v7'},scan_sequence:{version:'scan-sequence-v5'}};gripperState={unlocked:true};updatePlacementControls()");
assert(el('tubePlacementButton').disabled);
run("renderPoseResult({usable:true,selected_target:'basket',result_id:'basket-right',localization:{valid:true,right_shoulder_frame:'right_arm_sdk_world',point_right_shoulder_mm:[500,80,-400]},response:{}})");
assert(!el('tubePlacementButton').disabled);assert(el('boxPlacementButton').disabled);
assert(el('tubePlacementStatus').textContent.includes('软管预放置 Y=0'));
run("gripperState.unlocked=false;updatePlacementControls()");assert(el('tubePlacementButton').disabled);
run("gripperState.unlocked=true;serverStatus.placement.version='placement-v6';updatePlacementControls()");assert(el('tubePlacementButton').disabled);
run("serverStatus.placement.version='placement-v7';updatePlacementControls()");
const requests=[];let release;
ctx.fetch=async(url,o)=>{requests.push({url,body:JSON.parse(o.body)});await new Promise(r=>release=r);return{ok:true,json:async()=>({ok:true,data:{active:true,sku_typ:'tube'}})}};
(async()=>{
  const pending=el('tubePlacementButton').listeners.click[0]();
  assert(el('tubePlacementButton').disabled);assert(el('scanSequenceButton').disabled);
  await run("executePlacement('tube')");assert.equal(requests.length,1);
  assert.deepEqual(requests[0],{url:'/api/placement/start',body:{source_result_id:'basket-right',sku_typ:'tube'}});
  release();await pending;
  run("placementExecution={active:false};scanExecution={active:false};document.getElementById('poseTargetSelect').value='tube';updateScanControls()");
  assert(!el('scanSequenceButton').disabled);assert(el('scanSequenceStatus').textContent.includes('0/2'));
  assert(el('scanSequenceButton').textContent.includes('软管'));
  run("serverStatus.scan_sequence.version='scan-sequence-v4';updateScanControls()");assert(el('scanSequenceButton').disabled);
  run("serverStatus.scan_sequence.version='scan-sequence-v5';updateScanControls()");
  const scan=run('executeScanSequence()');await run('executeScanSequence()');
  assert.equal(requests.length,2);assert.deepEqual(requests[1],{url:'/api/scan-sequence/start',body:{sku_typ:'tube'}});
  release();await scan;
  console.log('PASS tube buttons: correct right basket, minus80, gripper/version gates, scan two photos, SKU payload and duplicate prevention');
})().catch(e=>{console.error(e);process.exitCode=1});
